name: CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Run Tests
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  security:
    name: Security Scan
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Run Nancy for Dependency Scanning
        uses: sonatype-nexus-community/nancy-github-action@main

  build:
    name: Build
    needs: [ test, security ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -v -o user-session-monitor-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/monitor

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-session-monitor-${{ matrix.goos }}-${{ matrix.goarch }}
          path: user-session-monitor-${{ matrix.goos }}-${{ matrix.goarch }}
          retention-days: 5
