name: Release

on:
  push:
    tags:
      - "v*" # 当推送 v 开头的标签时触发，如 v1.0.0

permissions:
  contents: write # 用于发布 release
  packages: write # 用于发布包

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的 git 历史用于生成更新日志

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # 使用最新的稳定版 Go
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
