name: Release

on:
  push:
    tags:
      - "v*" # 当推送 v 开头的 tag 时触发，如 v1.0.0

permissions:
  contents: write # 用于创建 release
  packages: write # 用于推送容器镜像

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Tag Format
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Must be in format v1.2.3"
            exit 1
          fi

  release:
    name: Create Release
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的 git 历史用于生成 changelog

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Generate Changelog
        id: changelog
        shell: bash
        run: |
          # 确保使用 LF 而不是 CRLF
          git config --global core.autocrlf false

          # 生成 changelog
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            # 如果是第一个 tag，获取所有提交
            echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
            git log --pretty=format:"* %s (%h)" >> "$GITHUB_OUTPUT"
            echo "" >> "$GITHUB_OUTPUT"  # 添加一个空行
            echo "EOF" >> "$GITHUB_OUTPUT"
          else
            # 获取从上一个 tag 到现在的提交
            echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
            git log --pretty=format:"* %s (%h)" "$PREVIOUS_TAG"..HEAD >> "$GITHUB_OUTPUT"
            echo "" >> "$GITHUB_OUTPUT"  # 添加一个空行
            echo "EOF" >> "$GITHUB_OUTPUT"
          fi

      - name: Set version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build for multiple platforms
        env:
          VERSION: ${{ steps.version.outputs.version }}
          CGO_ENABLED: 0
        run: |
          # 创建发布目录
          mkdir -p release

          # 定义 Linux 平台矩阵
          platforms=(
            "linux/amd64"    # x86_64
            "linux/arm64"    # ARM64/AArch64
            "linux/arm/v7"   # ARMv7 (树莓派等)
            "linux/arm/v6"   # ARMv6 (树莓派 Zero/1 等)
            "linux/386"      # x86 32位
            "linux/ppc64le"  # PowerPC 64-bit Little Endian
            "linux/s390x"    # IBM S/390x
            "linux/mips64le" # MIPS64 Little Endian
            "linux/mips64"   # MIPS64 Big Endian
          )

          # 构建所有平台
          for platform in "${platforms[@]}"; do
            # 解析操作系统和架构
            os=${platform%/*}
            arch=${platform#*/}
            
            # 处理 ARM 特殊情况
            if [[ $arch == "arm/v7" ]]; then
              arch="arm"
              export GOARM=7
            elif [[ $arch == "arm/v6" ]]; then
              arch="arm"
              export GOARM=6
            else
              unset GOARM
            fi

            echo "Building for $os/$arch..."
            GOOS=$os GOARCH=$arch go build -ldflags="-X main.version=${VERSION}" -o "release/user-session-monitor" ./cmd/monitor
            
            # 创建压缩包
            cd release
            if [[ $arch == "arm" && ! -z "$GOARM" ]]; then
              tar czf "user-session-monitor-${os}-${arch}v${GOARM}.tar.gz" "user-session-monitor"
            else
              tar czf "user-session-monitor-${os}-${arch}.tar.gz" "user-session-monitor"
            fi
            rm "user-session-monitor"
            cd ..
          done

          # 生成校验和
          cd release
          sha256sum *.tar.gz > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## 更新日志
            ${{ steps.changelog.outputs.changelog }}

            ## 安装说明
            1. 下载对应平台的压缩包
            2. 验证文件完整性：
               ```bash
               sha256sum -c checksums.txt
               ```
            3. 解压获取二进制文件：
               ```bash
               tar xzf user-session-monitor-*.tar.gz
               ```
            4. 参考 README.md 进行配置和安装

            ## 支持的 Linux 平台
            - x86_64 (amd64)
            - ARM64/AArch64 (arm64)
            - ARMv7 - 树莓派 2/3/4 等 (arm/v7)
            - ARMv6 - 树莓派 Zero/1 等 (arm/v6)
            - x86 32位 (386)
            - PowerPC 64-bit LE (ppc64le)
            - IBM S/390x (s390x)
            - MIPS64 LE (mips64le)
            - MIPS64 BE (mips64)

            ## 注意事项
            - 本程序仅支持 Linux 系统
            - 需要读取系统日志文件权限
            - 支持的日志文件路径：
              - Debian/Ubuntu: `/var/log/auth.log`
              - CentOS/RHEL: `/var/log/secure`
              - Amazon Linux: `/var/log/secure`
              - SUSE: `/var/log/messages`
          files: |
            release/*.tar.gz
            release/checksums.txt
          draft: false
          prerelease: false
          fail_on_unmatched_files: true

  docker:
    name: Build and Push Docker Image
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
